version: '2'

services:
  web:
    command: bundle exec puma -w 1 -t 1:16
    container_name: redmine_web
    expose:
      - "9292"
    image: my_redmine_development
    user: notroot
    volumes:
      - ../redmine:/work
      - ../secrets/:/secrets
    working_dir: /work
  mysql:
    container_name: redmine_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: mysql:5.7.16
    networks:
      - backend_network
    volumes:
      - ../import/:/import
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
