version: '2'

services:
  web:
    build:
      args:
        HOST_USER_UID: ${HOST_USER_UID}
        HOST_USER_GID: ${HOST_USER_GID}
      context: ..
      dockerfile: ./docker/Dockerfile.production
    image: my_redmine
