development:
  adapter:  mysql2
  database: redmine
  host:     mysql
  username: root
  password: root
  encoding: utf8

test:
  adapter:  mysql2
  database: redmine_test
  host:     mysql
  username: root
  password: root
  encoding: utf8

production:
  adapter:  mysql2
  database: <%= ENV['RAILS_DATABASE_NAME'    ] %>
  host:     <%= ENV['RAILS_DATABASE_HOST'    ] %>
  username: <%= ENV['RAILS_DATABASE_USER'    ] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  encoding: utf8
